version: '3.8'

services:

  # -----------------------------------------------
  # Setup Portainer
  #   Configuration for Austor
  #
  # https://hub.docker.com/r/portainer/portainer-ce
  # -----------------------------------------------
  portainer:
    #image:          portainer/portainer-ce:2.9.0
    #image:          portainer/portainer-ce:2.9.1
    #image:          portainer/portainer-ce:2.9.2
    #image:          portainer/portainer-ce:2.9.3
    #image:          portainer/portainer-ce:2.11.0
    #image:          portainer/portainer-ce:2.11.1
    #image:          portainer/portainer-ce:2.13.1 # password needed to be extended by 4 characters for this version
    #image:          portainer/portainer-ce:2.14.2
    #image:          portainer/portainer-ce:2.15.1
    #image:          portainer/portainer-ce:2.16.1
    #image:          portainer/portainer-ce:2.16.2
    #image:          portainer/portainer-ce:2.17.0
    #image:          portainer/portainer-ce:2.17.1
    #image:          portainer/portainer-ce:2.18.4
    image:          portainer/portainer-ce:2.20.1

    container_name: portainer-ce
    restart:        unless-stopped
    
    network_mode:   bridge
    ports:
      - "9000:9000/tcp" # http UI
      - "9443:9443/tcp" # https UI
      #- "8000:8000/tcp" # edge - TCP tunnel server over port
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/host:/data

      # Pass local timezone information to the container
      #- /etc/timezone:/etc/timezone:ro # not for Austor
      - /etc/localtime:/etc/localtime:ro
      
    labels:
      # docker-volume-backup will stop the container during backup
      - docker-volume-backup.stop-during-backup=true
