#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
version: '3'

services:

  # ----------------------------------
  # RabbitMQ service
  #
  #  https://hub.docker.com/_/rabbitmq
  # ----------------------------------
  rabbitmq:
    #image:                    "rabbitmq:3-management"
    #image:                    "rabbitmq:3.8.14-management"
    image:                    "rabbitmq:3.12.4-management"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: ${ENV_HAWKBIT_GENERIC_USER:?err}
      RABBITMQ_DEFAULT_PASS: ${ENV_HAWKBIT_GENERIC_PWD:?err}
    volumes:
      - ./data/host/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    hostname: hawkbit-rabbitmq  # persistent data is written using the hostname, if it is not set, huge disk space will be used
    ports:
      - "15672:15672"
      - "5672:5672"
    # Health check is mandatory so consumers of service dont start till this us up
    # Otherwise there are crashes
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "alarms"]
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "rabbitmq"

      # docker-volume-backup will stop the container during backup
      docker-volume-backup.stop-during-backup: true


  # ----------------------------------------------------------------------
  # MySQL service
  #  database (dont use 8 until hawkbit is updated from 0.3.0M7 to 0.3.0M9)
  #
  #  https://hub.docker.com/_/mysql
  # ----------------------------------------------------------------------
  mysql:
    #image:                  "mysql:5.7"
    image:                  "mysql:8.1.0"
    environment:
      MYSQL_DATABASE:       "hawkbit"
      MYSQL_USER:           "hawkbit"
      # Passwords saved persistently, this is for first boot ONLY (have to update in container after that)
      MYSQL_PASSWORD:       ${ENV_HAWKBIT_GENERIC_PWD:?err}
      MYSQL_ROOT_PASSWORD:  ${ENV_HAWKBIT_GENERIC_PWD:?err}
    volumes:
       - ./data/host/mysql:/var/lib/mysql
    restart: unless-stopped
    # Database doesnt needs to be accessed outside container so comment out
    #ports:
    #  - "3307:3306"
    healthcheck:
        test: ["CMD", "mysql", "--user=root", "--password=${ENV_HAWKBIT_GENERIC_PWD:?err}", "--execute", 'SHOW DATABASES;']
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "mysql"

      # docker-volume-backup will stop the container during backup
      docker-volume-backup.stop-during-backup: true

  # ----------------------------------------------------------
  # HawkBit simulator
  #
  #  https://hub.docker.com/r/hawkbit/hawkbit-device-simulator
  # ----------------------------------------------------------
  #hawkbit-simulator:
  #  image:                  "hawkbit/hawkbit-device-simulator:latest"
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    hawkbit:
  #      condition: service_healthy
  #  environment:
  #    - 'HAWKBIT_DEVICE_SIMULATOR_AUTOSTARTS_[0]_TENANT=DEFAULT'
  #    - 'SPRING_RABBITMQ_VIRTUALHOST=/'
  #    - 'SPRING_RABBITMQ_HOST=rabbitmq'
  #    - 'SPRING_RABBITMQ_PORT=5672'
  #    - 'SPRING_RABBITMQ_USERNAME=${ENV_HAWKBIT_GENERIC_USER:?err}'
  #    - 'SPRING_RABBITMQ_PASSWORD=${ENV_HAWKBIT_GENERIC_PWD:?err}'
  #  restart: unless-stopped
  #  ports:
  #    - "8083:8083"
  #  labels:
  #    NAME: "hawkbit-simulator"


  # -------------------------------------------------------
  # HawkBit service
  #  update server
  #
  #  https://hub.docker.com/r/hawkbit/hawkbit-update-server
  # -------------------------------------------------------
  hawkbit:
    #image:                  "hawkbit/hawkbit-update-server:latest-mysql"
    #image:                  "hawkbit/hawkbit-update-server:0.3.0M7-mysql"
    image:                  "hawkbit/hawkbit-update-server:0.3.0M9-mysql"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/hawkbit",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.rabbitmq.username": "${ENV_HAWKBIT_GENERIC_USER:?err}",
        "spring.rabbitmq.password": "${ENV_HAWKBIT_GENERIC_PWD:?err}",
        "spring.datasource.username": "hawkbit",
        "spring.datasource.password": "${ENV_HAWKBIT_GENERIC_PWD:?err}",
        "hawkbit.server.im.users[0].username": "${ENV_HAWKBIT_GENERIC_USER:?err}",
        "hawkbit.server.im.users[0].password": "{noop}${ENV_HAWKBIT_GENERIC_PWD:?err}",
        "hawkbit.server.im.users[0].firstname": "${ENV_HAWKBIT_GENERIC_USER:?err}",
        "hawkbit.server.im.users[0].lastname": "",
        "hawkbit.server.im.users[0].email": "${ENV_HAWKBIT_GENERIC_EMAIL:?err}",
        "hawkbit.server.im.users[0].permissions": "ALL"
        }'
      #- 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hawkbit'
      #- 'SPRING_RABBITMQ_HOST=rabbitmq'
      #- 'SPRING_RABBITMQ_USERNAME=guest'
      #- 'SPRING_RABBITMQ_PASSWORD=guest'
      #- 'SPRING_DATASOURCE_USERNAME=hawkbit'
      #- 'SPRING_DATASOURCE_PASSWORD=password'
    volumes:
      - ./data/host/hawkbit/data:/opt/hawkbit/data
      - ./data/host/hawkbit/artifactrepo:/opt/hawkbit/artifactrepo
    restart: unless-stopped
    ports:
      - "9090:8080"
    healthcheck:
        test: ["CMD", "nc", "-zv", "hawkbit", "8080"]
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "hawkbit"
      
      # docker-volume-backup will stop the container during backup
      docker-volume-backup.stop-during-backup: true


  # ----------------------------------
  # Adminer service
  #  database admin
  #
  #  https://hub.docker.com/_/adminer/
  # ----------------------------------
  adminer:
    #image:                    "adminer:4.8.0-standalone"
    image:                    "adminer:4.8.1-standalone"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: "mysql:3306"
    restart: unless-stopped
    ports:
      - "9091:8080"
    labels:
      NAME: "adminer"

      # docker-volume-backup will stop the container during backup
      docker-volume-backup.stop-during-backup: true
