version: '3.0'

services:

  # ------------------------------------------
  # Setup dokuwiki (V1 - old server)
  #
  #  https://hub.docker.com/r/bitnami/dokuwiki
  # ------------------------------------------
  dokuwiki-v1:
    image:          bitnami/dokuwiki:20200729
    container_name: dokuwiki-v1
    restart:        unless-stopped

    ports:
      - '9081:8080'
      - '9444:8443'

    environment:
      - DOKUWIKI_USERNAME=${ENV_DOKUWIKI_USER_NAME:?err}
      - DOKUWIKI_FULL_NAME=${ENV_DOKUWIKI_FULL_NAME:?err}
      - DOKUWIKI_PASSWORD=${ENV_DOKUWIKI_PASSWORD:?err}
      - DOKUWIKI_EMAIL=${ENV_DOKUWIKI_EMAIL:?err}
      - DOKUWIKI_WIKI_NAME=max.lan notes

    volumes:
      # As per the bitnami dockerhub instructions - to the share please apply 'chown 1001:users * -R'
      - ./data/host/:/bitnami/dokuwiki/

