version: '3.8'

services:

  # ----------------------------------------
  # Setup Portainer Agent
  #   Configuration for Austor
  #
  # https://hub.docker.com/r/portainer/agent
  # ----------------------------------------
  portainer-agent:
    #image:          portainer/agent:2.13.1
    #image:          portainer/agent:2.15.1
    #image:          portainer/agent:2.16.1
    #image:          portainer/agent:2.16.2
    #image:          portainer/agent:2.17.0
    #image:          portainer/agent:2.17.1
    image:          portainer/agent:2.18.4

    container_name: portainer-agent
    restart:        unless-stopped
    
    network_mode:   bridge
    ports:
      - "9001:9001/tcp" # agent port

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/.@plugins/AppCentral/docker-ce/docker_lib/volumes:/var/lib/docker/volumes # Austor centric

      # Pass local timezone information to the container
      #- /etc/timezone:/etc/timezone:ro # not for Austor
      - /etc/localtime:/etc/localtime:ro
